Repository dogecoin/ltc-scrypt, pull requests merged in 2022-08, with the labels that each got.

#6 add readme
  README.md
Labels: documentation

#9 qa: create a ci
  .github/workflows/ci.yml
  test.py
Labels: qa

#11 fixate v1.0.1
  setup.py
Labels: urgent
